apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrations
spec:
  backoffLimit: 10 # Number of retries before marking Job as failed
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alembic-migrations
          image: l8bloom-frontier:5000/api_server:0.0.5
          imagePullPolicy: IfNotPresent
          command: ["alembic"]
          args: ["upgrade", "head"]
          env:
            - name: PG_HOST
              value: "postgres-service"
            - name: PG_PORT
              value: "7777"
            - name: PG_USER
              value: "postgres"
            - name: PG_PASSWORD
              value: "postgres"
            - name: PG_DATABASE
              value: "qwen"
