# Source: ray-cluster/templates/raycluster-cluster.yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-kuberay
  namespace: default
  labels:
    helm.sh/chart: ray-cluster-1.6.1
spec:
  rayVersion: "2.55.1"
  headGroupSpec:
    serviceType: ClusterIP
    template:
      metadata:
        labels:
          helm.sh/chart: ray-cluster-1.6.1
      spec:
        containers:
          - name: ray-head
            image: l8bloom-frontier:5000/ray:0.0.7
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /tmp/ray
                name: log-volume
            resources:
              limits:
                cpu: "2"
                memory: 10Gi
              requests:
                cpu: "2"
                memory: 5Gi
        volumes:
          - emptyDir: {}
            name: log-volume
  workerGroupSpecs:
    - groupName: workergroup
      replicas: 1
      minReplicas: 1
      maxReplicas: 1
      numOfHosts: 1
      template:
        metadata:
          labels:
            helm.sh/chart: ray-cluster-1.6.1
        spec:
          containers:
            - name: ray-worker
              image: l8bloom-frontier:5000/ray:0.0.7
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /tmp/ray
                  name: log-volume
                - mountPath: /model
                  name: qwen-model
              resources:
                limits:
                  cpu: "8"
                  memory: 8Gi
                  amd.com/gpu: 1
                requests:
                  cpu: "8"
                  memory: 8Gi
          volumes:
            - name: log-volume
              emptyDir: {}
            - name: qwen-model
              hostPath:
                path: "/models/models--Qwen--Qwen2.5-0.5B-Instruct"
                type: Directory
