"""add metric columns to batches table

Revision ID: 12c06d5629ba
Revises: c15117f716b3
Create Date: 2026-05-03 14:19:56.076294

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12c06d5629ba"
down_revision: str | Sequence[str] | None = "c15117f716b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("batches", sa.Column("total_in_tokens", sa.Integer(), nullable=True))
    op.add_column("batches", sa.Column("total_out_tokens", sa.Integer(), nullable=True))
    op.add_column("batches", sa.Column("tokens_per_second", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("batches", "tokens_per_second")
    op.drop_column("batches", "total_out_tokens")
    op.drop_column("batches", "total_in_tokens")
    # ### end Alembic commands ###
